### ISSUE TITLE
Leftover semantic hilighting after killing a runaway idris

### ISSUE THREAD

**Issue by Melvar** [idris-hackers/idris-mode#341]
With my interpolation file loaded, I entered 

```
λΠ> :let f : String -> String -> String; f t foo = interpolate t
```

This happens to run away and guzzle memory, so I killed Idris externally. After reloading after that, which restarted Idris as expected, there are a few bits of semantic hilighting relating to that input in the fresh `*idris-repl*`, in particular in the version string at the top:

![Hilighting](http://i.imgur.com/3O4yHhg.png)

The purple part on the left shows `String : Type, Strings in some unspecified encoding, <mouse-3> context menu` on mouseover, the yellow part shows `f : String -> String -> String, , <mouse-3> context menu`. (The colors are my config for types and functions respectively, so as to not clash with other things in this theme.) The magenta parts show nothing. This seems to correspond to the section `> String; f t foo = interp` of the original input.

**Comment by david-christiansen** [comment]
Just as an FYI, you can kill a misbehaving Idris with `M-x idris-quit`. Probably when Idris starts up, it should go delete all old semantic highlights that are sticking around. Usually, killing Idris also kills its error buffers and the like, but I left the highlighting around to make code more readable. This isn't a problem in source buffers because loading them deletes their obsolete annotations anyway, but it's wrong in a REPL buffer.

**Comment by david-christiansen** [comment]
Are you still able to reproduce this? I just gave it an attempt and couldn't.

**Comment by abailly** [comment]
@Melvar Is this still relevant?

**Comment by Melvar** [comment]
I don’t actually know since I’m not using idris-mode anymore. I expect it can be closed.
