### ISSUE TITLE
Running idris-case-split inside something already case-split deletes the line

### ISSUE THREAD

**Issue by pharpend** [idris-hackers/idris-mode#362]
Here's the starting file:

```idris
module Time

import Data.So

data Time : Type where
  MkTime : (hours : Int)
        -> (mins : Int)
        -> (secs : Int)
        -> So (mins < 60)
        -> So (secs < 60)
        -> Time
        
instance Semigroup Time where
```

Move point to inside the word `Semigroup`, and hit `C-c C-s`:

```idris
instance Semigroup Time where
    (<+>) x x1 = ?Semigroup_rhs_1
```

Move to `x`, hit `C-c C-c`:

```idris
instance Semigroup Time where
    (<+>) (MkTime hours mins secs x y) x1 = ?Semigroup_rhs_2
```

Move to either the `x` or the `y`, hit `C-c C-c`:

```idris
instance Semigroup Time where

```

`So ...` has one proof: `Oh`. Idris-mode should pattern-match `Oh` instead of just deleting the line.

**Comment by david-christiansen** [comment]
When the compiler can't produce a case split for something, it just produces nothing. In this case, it doesn't have a reason to think that the dynamic check has been performed, so it makes sense that the `Oh` pattern does't work.

Perhaps `idris-mode` should detect a blank output and then respond with a message like "Can't case split x" instead of just killing the case though.

**Comment by hannesm** [comment]
in a perfect world the compiler would not send an empty string, but an error message instead of patching around this in the users of the ide mode.

**Comment by david-christiansen** [comment]
I agree. But for various reasons, this will be a bit difficult to make happen, because sometimes the right thing to do is in fact to remove the case.  In the meantime, we can hack around it fairly easily here, so I want to do this, but in the long run having something like Agda's absurd pattern would make the language more usable here, as the compiler would have something better to return.
