### ISSUE TITLE
Error "Symbol's function definition is void" on interactive theorem prover

### ISSUE THREAD

**Issue by gonzaw** [idris-hackers/idris-mode#379]
Hi.

Whenever I start the interactive theorem prover, after I input a tactic and press M-n I get the following message error:
**Symbol's function definition is void: lexical let**

Afterwards, technically the tactic is applied and the metavariables are updated in the corresponding buffer. However, the buffer with the used tactics gets a duplicated tactic and can't be manipulated easily (the duplicated tactic is read-only)

For example, if I write the "intros" tactic, after pressing M-n I get the above message error, and a second "intros" tactic appears right below the one I wrote. 
The same thing happens if I press M-p (retract) right afterwards

**Comment by david-christiansen** [comment]
This is due to a use of the CL package at runtime in some code we inherited from DIME, which is older than Emacs's native lexical scoping. For some reason, the last time I tried rewriting the code to not use the CL package, it didn't actually work, so there's some difference in the semantics which I haven't yet figured out. I'll have another go at it soon - in the meantime, you should be able to work around the problem by doing a `(require 'cl)` first.

Does that work-around help?

**Comment by gonzaw** [comment]
Hi. I added `(require 'cl)` to my init.el file and loaded it, but the problem still persists

**Comment by david-christiansen** [comment]
This is odd. I can't reproduce it. What specific versions of idris-mode, Idris, and Emacs are you running?

**Comment by gonzaw** [comment]
Hi. Sorry for the wait.

Here are my versions:

*Emacs:* GNU Emacs 24.3.1 
*Idris:* 0.19.8
*Idris-mode:* 20150523.719

I'm planning on updating to idris 0.19.9 and to the new version of idris-mode, so maybe those updates can solve this issue.

**Comment by david-christiansen** [comment]
Glad to hear it! Thanks for the update!
