### ISSUE TITLE
Search failed with idris-make-lemma

### ISSUE THREAD

**Issue by pmwhite** [idris-hackers/idris-mode#437]
I'm trying to work through the example in the docs for proving that addition of natural numbers commutes. Here's the code so far:

    module PlusCommutes

    plus_commutes : (n : Nat) -> (m : Nat) -> n + m = m + n
    plus_commutes Z m = ?plus_commutes_rhs_1
    plus_commutes (S k) m = ?hole

Putting my cursor over a letter in `?plus_commutes_rhs_1`, and try to do `idris-make-lemma`, I get an error saying `Search Failed: "^\\(\\s-*\\)\\(([^)]+)\\|\\w+\\)\\s-*:"`

I've tried to think about what the problem could be. On other functions, `idris-make-lemma` works; I think perhaps the issue with this one is that there are parenthesis in the type.

**Comment by Jebes** [comment]
Hello, I was able to reproduce and fix this.

Changing the regex to be `""^\\(\\s-*\\)\\(([^)]+)\\)\\|\\w+\\s-*:" instead of `"^\\(\\s-*\\)\\(([^)]+)\\|\\w+\\)\\s-*:"` resolves the regex searching issue. Come to find out this reveals another issue: when there is no indentation the local `indentation` variable is set to nil. Adding a guard for that fixes the problem as well. 

Emacs version: 26.1 on Fedora 28.1

**Comment by ohad** [comment]
This fix doesn't work for me, and I get:
```let: Wrong type argument: char-or-string-p, nil```
with the above example.

I think the problem has to do with underscores:

```
_a : Nat
_a = ?lem1 -- idris-make-lemma (C-c C-e) produces: 
          -- let: Search failed: "^\\(\\s-*\\)\\(([^)]+)\\|\\w+\\)\\s-*:"

b : Nat
b = ?lem2 -- idris-make-lemma (C-c C-e) works as expected

_c : Nat
_c = ?lem3 -- idris-make-lemma (C-c C-e) works, but places lemma
           -- before b
```
